# ====================| MELT's KITTY CONFIG |====================

## --- theme ---

# nightfox theme is already handled here:
include current-theme.conf

## --- fonts ---

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
disable_ligatures never

## --- cursor ---

cursor_shape          block
cursor_blink_interval 0
shell_integration     no-cursor

## visual trail

cursor_trail          3
cursor_trail_decay    0.1 0.4

## --- window layout ---

# padding
window_padding_width 5
confirm_os_window_close 0

# no titlebar (sway handles this)
hide_window_decorations yes

## --- performance ---

# match my monitor refresh rate
repaint_delay    8
input_delay      2
sync_to_monitor  yes

# --- bell ---
enable_audio_bell no
visual_bell_duration 0.0

# --- scrollback ---
scrollback_lines 5000

## --- mouse ---

# hide mouse after 3 seconds of typing

mouse_hide_wait 3.0
url_color #50a5a4
url_style curly
detect_urls yes

## --- tab bar ---

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
active_tab_font_style   bold
inactive_tab_font_style normal

## --- advanced ---

# close the window when the shell exits

close_on_child_death yes
allow_remote_control yes

# ensure wayland is used

linux_display_server wayland

## --- keybindings ---

# open new tabs in same directory

map ctrl+shift+t new_tab_with_cwd

# quick config reload

map ctrl+shift+f5 load_config_file