# vim:ft=kitty

### ====================| MELT's KITTY CONFIG |====================

# (modus-vivendi, electric cyan)

# --- fonts ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- transparency & layout ---
background_opacity         0.85
dynamic_background_opacity yes
window_padding_width       4
confirm_os_window_close    0

# --- core colors ---
background            #000000
foreground            #ffffff
selection_background  #535353
selection_foreground  #ffffff
url_color             #04A9E4

# --- cursor ---
cursor                #ffffff
cursor_text_color     #000000

# --- borders & tabs ---
active_border_color   #04A9E4
inactive_border_color #646464
bell_border_color     #ff8059

active_tab_background   #04A9E4
active_tab_foreground   #000000
inactive_tab_background #1e1e1e
inactive_tab_foreground #989898

## ---------- ansi colors ----------

# black
color0 #000000
color8 #535353

# red
color1 #ff8059
color9 #ff8059

# green
color2 #44bc44
color10 #44bc44

# yellow
color3 #B3A203
color11 #B3A203

# blue (accent)
color4 #04A9E4
color12 #04A9E4

# magenta
color5 #989898
color13 #ffffff

# cyan (accent)
color6 #04A9E4
color14 #04A9E4

# white
color7 #989898
color15 #ffffff

### ====================| END KITTY CONFIG |====================