# ====================| MELT's SYSTEMD CLEANUP CONFIG |===============
# Type  Path                      Mode UID  GID  Age
d       %h/pics/screenshots       0755 melt melt 1d
d       %h/downloads              0755 melt melt 2d
d       %h/clips                  0755 melt melt 2d
d       %h/inbox                  0755 melt melt 2d