### ========== VARIABLES MODULE ==========

set $mod Mod4
set $left h
set $down j
set $up k
set $right l

set $term kitty
set $rofi_cmd rofi -terminal '$term'
set $menu $rofi_cmd -show combi -combi-modes drun
set $windows $rofi_cmd -show window

### ========== END VARIABLES MODULE ==========