
### ========== PERIPHERAL MODULE ==========

# ----- input -----
input * {
  xkb_layout us,it
  xkb_options grp:win_space_toggle
}

# ----- output -----
output eDP-1 resolution 1920x1080 position 0,0
output HDMI-A-1 resolution 1920x1080@100Hz position 1920,0

### ========== END PERIPHERAL MODULE ==========