
### ========== PERIPHERAL MODULE ==========

# ----- input -----
input * {
  xkb_layout us,it
  xkb_options grp:win_space_toggle
}

# ----- output -----
output eDP-1 resolution 1920x1080 position 0,0
output HDMI-A-1 resolution 1920x1080 position 1920,0

# assign workspaces to specific monitors
workspace 1 output eDP-1
workspace 2 output HDMI-A-1
workspace 3 output HDMI-A-1
workspace 4 output HDMI-A-1

### ========== END PERIPHERAL MODULE ==========