
### ========== AUTOSTART MODULE ==========

exec dbus-update-activation-environment --all

exec_always "pkill waybar || true; waybar > /dev/null 2>&1 &"

exec_always "pkill dunst || true; dunst &"

### ========== END AUTOSTART MODULE ==========