### ========== AUTOSTART MODULE ==========

# update d-bus environment
exec dbus-update-activation-environment --all

# ui components
exec_always "pkill waybar; waybar > /dev/null 2>&1 &"
exec_always "pkill dunst; dunst &"

# battery check loop
exec_always "pkill -f check_battery.sh; while true; do /home/melt/.local/bin/check_battery.sh; sleep 300; done"

### ========== END AUTOSTART MODULE ==========