### ========== AUTOSTART MODULE ==========

# update d-bus environment
exec dbus-update-activation-environment --all

# ui components
exec_always "pkill waybar || true; waybar > /dev/null 2>&1 &"
exec_always "pkill dunst || true; dunst &"

# eye protection
exec gammastep -l 45.4:9.1 -t 5700:3600 -g 0.8 -m wayland &

# battery check loop
exec_always "pkill -f battery_check.sh; while true; do ~/dotfiles/scripts/battery_check.sh; sleep 300; done"

### ========== END AUTOSTART MODULE ==========