for_window [app_id="picker"] floating enable, border pixel 2, resize set 950 600, move position center

for_window [class="picker"] floating enable, border pixel 2, resize set 950 600, move position center

