
### ========== THEME MODULE ==========

# ----- colors -----
set $cyan #50a5a4
set $bg_dark #192330
set $bg_medium #2d3848
set $fg_light #cdcecf
set $fg_dark #6b7a8c
set $red #c94f6d

# ----- windows setting -----
for_window [class=".*"] border pixel 2
for_window [app_id="kitty"] opacity 0.95
for_window [app_id="emacs"] opacity 1

# window colors
client.focused $cyan $bg_medium $fg_light $cyan $cyan
client.unfocused $bg_dark $bg_dark $fg_dark $bg_dark $bg_dark
client.focused_inactive $bg_dark $bg_dark $fg_dark $bg_dark $bg_dark
client.urgent $red $red $fg_light $red $red

# ----- wallpaper -----
output * bg ~/pics/wallpapers/moon.png fill

### ========== END THEME MODULE ==========