### ========== THEME MODULE ==========

# colors
set $cyan     #04A9E4
set $bg_dark  #000000
set $bg_med   #1e1e1e
set $border   #646464
set $fg_light #ffffff
set $fg_dark  #989898
set $red      #ff8059

# window borders and opacity
for_window [class=".*"] border pixel 2
# for_window [app_id="kitty"] opacity 0.95
for_window [app_id="emacs"] opacity 1

# window colors
client.focused $cyan $bg_med $fg_light $cyan $cyan
client.unfocused $bg_dark $bg_dark $fg_dark $bg_dark $bg_dark
client.focused_inactive $border $border $fg_dark $border $border
client.urgent $red $red $fg_light $red $red

# wallpaper
output * bg /home/melt/pics/wallpapers/colons.png fill

### ========== END THEME MODULE ==========