[preferred]
# Di default usa gtk per le varie funzioni di sistema (es. notifiche o print)
default=gtk
# Per la selezione dei file (FileChooser), usa termfilechooser
org.freedesktop.impl.portal.FileChooser=termfilechooser